name: Download a file
description: "Download a file from a URL and save it to the target path"
branding:
  icon: "download"
  color: "orange"
inputs:
  url:
    description: "URL to file"
    required: true
  target-path:
    description: "Target path"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: 📥 Download a file
      run: wget -nc -P ${{ inputs.target-path }} ${{ inputs.url }}
      shell: bash
